#####  ML勉強会第1回（阿久津朋美）　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
# Section.1 初めに..

##  なぜ機械学習か？
・環境が整備された   
    １．コンピュータ、計算機技術の発展（高速化、低コスト化）  
    ２．データ整備の発展  
    ３．実装が容易    
・機械学習で解決可能な問題  
    １．教師あり学習　既知の例を一般化する　ー　文字認識、画像判断、異常値検出  
    ２．教師なし学習　分類（法則）を作る  
・データを理解し、解決しようとしている問題とデータの関係を理解することが重要   

## なぜPython？  
* 汎用言語(C言語)とスクリプト言語(Matlab, R)の使いやすさを合わせ持つ  
* 可視化、統計、自然言語処理、画像処理のライブラリが用意されている。  
* scikit-learnに様々な機械学習アルゴリズムが用意されている。

## scikit-learn  
様々な機械学習アルゴリズムが用意されている。2つのPythonパッケージNumPy, SciPyに依存している。  
* アルゴリズムのドキュメント(http://scikit-learn.org/stable/documentation)
* ユーザーガイド(http://scikit-learn.org/stable/user_guide.html)

## これから使用していくライブラリとツール

## Jupyter Notebook　
Jupyter notebookはIpython notebookのこと。  
＊以下、ORセミナーの資料を一部拝借

### 対話型シェルIPython (http://ipython.org)

* IPython は，Pythonシェルを使いやすく機能強化したもの、インタラクティブシェル

### IPythonシェルの便利な機能
* ヘルプ機能
* 補完（completion)
* 履歴
* マジック関数
* システムコマンド
* その他

#### 1. ヘルプ機能
* '?' でIPythonのヘルプメッセージが現れる．
* 先頭や末尾に'?'を追加し "?object"や"object?"とするとobjectのヘルプが見られる．
* '??'だとさらに詳しいヘルプ(もしあれば）．

#### 2. tabキーによる補完(completion)
* 'p'のあと空けずに[tab]キーを打つとpから始まる候補があらわれる．
- 自分で定義した関数や、変数、import したライブラリの関数などにも適用される． 

#### 3.履歴
* 'history' コマンドで、過去の入力が一斉に表示される．
- [ctrl-n,p]や矢印で、前の入力が順に表示される．??
- _ih, _oh は入力や出力が記録されたリスト．

#### 4.マジック関数(マジックコマンド)
* IPython自体のコントロール＋システム系のコマンド
- 先頭に'%'や'%%'がついたコマンド
- '%'はラインマジック（１行），'%%'はセルマジック（複数行）
- 例：%time, %timeit, %%time, %%timeit は，後に続くコマンドの実行時間を計る．
- 例：%who, %who_ls, %rest_selective, %reset は，名前空間の制御
- 例：%save, %edit, %run 履歴をファイル保存，編集，実行

などがある．

#### 5.システムコマンド
* OSのコマンドを実行できる．
- 先頭に'!'をつける．例：'!date'（Unixの日付を調べるコマンド）．
- コマンドの実行結果を文字列として受け取ることができる．例：s = !date

### Jupyter Notebookの概要(http://jupyter.org/)
* Pythonコード(出力を含む)，文章，画像（動画），音声，TeXの簡単な数式などを，  Notebookという一つのファイルで扱う．
- 編集はWebブラウザーで．
- 立ち上げは，'jupyter notebook'　というコマンド
- バックグラウンドで Pythonカーネルが動作
- 編集即実行で，多彩なプログラミングと文書作成が期待できる．
- Python以外のプログラミング言語もサポート

##### IPython interact 機能の例

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

f = lambda x: x**3 - x +1
g = lambda x: 3*x**2 - 1
f2 = lambda a,x: g(a)*(x-a)+f(a)

def mydraw(接点のx座標, 色):
    x = np.linspace(-2.0,2.0)
    y1 = f(x)
    y2 = f2(接点のx座標,x)
    plt.plot(x,y1)
    plt.plot(x,y2,color=色[0])
    plt.show()

interact(mydraw, 接点のx座標=(-2.0, 2.0), 色=['red', 'green']);

##  NumPy   
* 多次元配列機能や線形代数、フーリエ変換、疑似乱数生成器などの高レベルの数学関数　
* scikit-learnはNumPy配列で入力を受け取る

In [8]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


##  SciPy

* 高度な線形代数ルーチン、数学関数の最適化、信号処理、特殊な数学関数、統計分布の機能を持つ。
* scikit-learnがSciPyの関数群を利用
* 疎行列を生成 scipy.sparse

In [10]:
from scipy import sparse
eye=np.eye(4)
print("NumPy array:\n{}".format(eye))
sparse_matrix=sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


SciPy Lecture Notes (http://www.scipy-lectures.org/)

In [13]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO representation:\n{}".format(eye_coo))

COO representation:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


## matplotlib

* グラフ描画ライブラリ
* Jupyterでは%matplotlib notebook/%matplotlib inlineコマンドを用いると、ブラウザ上に図を直接表示することが可能

## pandas

* データフレーム
* 詳細は別資料参考

## mglearn

* Amuellerが書いたコードで、本の中に用いられている。
* GitHub (https://github.com/amueller/introduction_to_ml_with_python)
* 使用には、以下のimportが必要  
    import numpy as np  
    import matplotlib.pyplot as plt  
    import pandas as pd  
    import mglearn  
    from IPython.display import display  

## アプリケーション例